routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::middleware(['notLogin'])->group(function() {
  Route::get('dashboard','MainController@index')->name('dashboard.index');
  Route::post('loglogin/dataTables','MainController@datatables')->name('loglogin.dataTables');
  Route::post('auth/requestLoginUser/{auth}','AuthController@UserRequestLogin')->name('auth.requestLoginUser');
  Route::resource('kategori','KategoriController');
  Route::resource('barang','BarangController');

  Route::middleware(['slugpermission'])->group(function() {
    Route::resource('pegawai','PegawaiController');
    Route::resource('jabatan','JabatanController');
    Route::get('skp','StatusKepegawaianController@index')->name('skp.index');
    Route::post('jabatan/update','JabatanController@update')->name('jabatan.update');
    Route::post('pegawai/update','PegawaiController@update')->name('pegawai.update');
    Route::post('pegawai/dataTables','PegawaiController@datatables')->name('pegawai.dataTables');
    Route::post('jabatan/dataTables','JabatanController@datatables')->name('jabatan.dataTables');
    Route::post('skp/dataTables','StatusKepegawaianController@datatables')->name('skp.dataTables');
    Route::post('pegawai/requestAct/{pegawai}','PegawaiController@requestAct')->name('pegawai.requestAct');
    Route::post('skp','StatusKepegawaianController@store')->name('skp.store');
    Route::get('skp/{skp}/edit','StatusKepegawaianController@edit')->name('skp.edit');
    Route::post('skp/update','StatusKepegawaianController@update')->name('skp.update');
    Route::delete('skp/{skp}','StatusKepegawaianController@destroy')->name('skp.destroy');
  });

  Route::get('pegawai/{pegawai}','PegawaiController@show')->name('pegawai.show');
  Route::post('barang/update','BarangController@update')->name('barang.update');
  Route::post('kategori/dataTables','KategoriController@datatables')->name('kategori.dataTables');
  Route::post('barang/dataTables','BarangController@datatables')->name('barang.dataTables');
  Route::get('leaflet/maps','LeafletController@index')->name('leaflet.index');
});

app/Models/Barang.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Barang extends Main
{
    protected $table = 'master.barang';

    protected $fillable = [
      'kode_barang',
      'nama_barang',
      'uuid_kategori',
      'manufaktur_barang',
      'jumlah_stok_barang',
      'harga_per_satuan_barang'
    ];

    public function KategoriBarang() {
      return $this->belongsTo(KategoriBarang::class,'uuid_kategori','uuid');
    }
}

app/Http/Controllers/BarangController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Barang;
use App\Models\KategoriBarang;
use App\Models\Validation;
use DB;
use DataTables;
use Validator;

class BarangController extends Controller
{

    public function datatables() {
      $query = Barang::with([
        'KategoriBarang'
      ])->select('barang.*');
      return Datatables::of($query)
              ->addIndexColumn()
              ->addColumn('action', function($data) {
                 $button = '<button type="button" name="delete" id="'.route('barang.destroy',$data->uuid).'" class="delete btn btn-danger btn-sm"><i class = "fa fa-trash"></i></button> ';
                 $button .= '<button type="button" name="update" id="'.route('barang.edit',$data->uuid).'" class="update btn btn-warning btn-sm"><i class = "fa fa-edit"></i></button>';
                 return $button;
               })
              ->rawColumns(['action'])
              ->make(true);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $data['kategori'] = DB::table('master.kategori_barang')
                            ->select('uuid','nama_kategori')
                            ->where('deleted_at',null)
                            ->get();
        return view('AdminLTE.pages.barang.list',compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $rules = array(
          'kode_barang' => 'required',
          'nama_barang' => 'required',
          'uuid_kategori' => 'required',
          'manufaktur_barang' => 'required',
          'jumlah_stok_barang' => 'required',
          'harga_per_satuan_barang' => 'required'
        );
        $errors = Validator::make(
          $request->all(),
          $rules,
          Validation::ValidationMessage(),
        );

        if($errors->fails()) {
          return response()->json([
            'response' => 'failed',
            'header' => 'Gagal',
            'messages' => $errors->errors()->all(),
          ]);
        }

        DB::beginTransaction();

        $request->request->add([
          'kode_barang' => $request->kode_barang,
          'nama_barang' => $request->nama_barang,
          'uuid_kategori' => $request->uuid_kategori,
          'manufaktur_barang' => $request->manufaktur_barang,
          'jumlah_stok_barang' => $request->jumlah_stok_barang,
          'harga_per_satuan_barang' => $request->harga_per_satuan_barang
        ]);

        $insert = Barang::create($request->all());

        if($insert) {
          DB::commit();
          return response()->json([
            'response' => 'success',
            'header' => 'Sukses',
            'messages' => 'Data Sukses Tersimpan',
            'post_data' => $request
          ]);
        } else {
          DB::rollback();
          return response()->json([
            'response' => 'failed',
            'header' => 'Gagal',
            'messages' => 'Data Gagal Tersimpan',
          ]);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($uuid)
    {
        //
        $data = Barang::where('uuid',$uuid)->firstOrFail();
        return response()->json([
          'response' => 'success',
          'data' => $data
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        //
        //
        $rules = array(
          'kode_barang' => 'required',
          'nama_barang' => 'required',
          'uuid_kategori' => 'required',
          'manufaktur_barang' => 'required',
          'jumlah_stok_barang' => 'required',
          'harga_per_satuan_barang' => 'required'
        );
        $errors = Validator::make(
          $request->all(),
          $rules,
          Validation::ValidationMessage(),
        );

        if($errors->fails()) {
          return response()->json([
            'response' => 'failed',
            'header' => 'Gagal',
            'messages' => $errors->errors()->all(),
          ]);
        }

        DB::beginTransaction();

        $request->request->add([
          'kode_barang' => $request->kode_barang,
          'nama_barang' => $request->nama_barang,
          'uuid_kategori' => $request->uuid_kategori,
          'manufaktur_barang' => $request->manufaktur_barang,
          'jumlah_stok_barang' => $request->jumlah_stok_barang,
          'harga_per_satuan_barang' => $request->harga_per_satuan_barang
        ]);

        $barang = Barang::where('uuid',$request->uuid)->firstOrFail();
        $update = $barang->update($request->all());

        if($update) {
          DB::commit();
          return response()->json([
            'response' => 'success',
            'header' => 'Sukses',
            'messages' => 'Data Sukses Dirubah',
            'post_data' => $request
          ]);
        } else {
          DB::rollback();
          return response()->json([
            'response' => 'failed',
            'header' => 'Gagal',
            'messages' => 'Data Gagal Tersimpan',
          ]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($uuid)
    {
        //
        $data = Barang::where('uuid',$uuid)->firstOrFail();
        $delete = $data->delete();
        if($delete) {
          return response()->json([
            'response' => 'success',
            'header' => 'Sukses',
            'messages' => 'Data Sukses Terhapus'
          ]);
        } else if(!$delete) {
          return response()->json([
            'response' => 'failed',
            'header' => 'Gagal',
            'messages' => 'Data Gagal Terhapus'
          ]);
        }
    }
}

resources/views/AdminLTE/pages/barang/list.blade.php
@extends('AdminLTE.app')

@section('content')

<div class="row">
  <div class="col-md-12">
    <div class="card card-primary">
      <div class="card-header">
        <h3 class="card-title">Tambah Barang</h3>
      </div>
        <form id="barang_form" method="post" enctype="multipart/form-data">
          @csrf
          <div class="card-body">
            <div class="form-group">
              <div class="row">
                <div class="col-6">
                  <input type="text" class="form-control" id="kode_barang" name="kode_barang" placeholder="Kode Barang">
                </div>
                <div class="col-6">
                  <input type="text" class="form-control" id="nama_barang" name="nama_barang" placeholder="Nama Barang">
                </div>
              </div>
            </br>
              <div class="row">
                <div class="col-6">
                  <input type="text" class="form-control" id="manufaktur_barang" name="manufaktur_barang" placeholder="Manufaktur Barang">
                </div>
                <div class="col-6">
                  <select class="form-control select2" style="width: 100%;" id= "uuid_kategori" name="uuid_kategori">
                    <option></option>
                    @foreach($data['kategori'] as $kategori)
                      <option value="{{ $kategori->uuid }}">{{ $kategori->nama_kategori }}</option>
                    @endforeach
                  </select>
                </div>
              </div>
            <br/>
            <div class="row">
              <div class="col-6">
                <input type="number" class="form-control" id="jumlah_stok_barang" name="jumlah_stok_barang" placeholder="Jumlah Stok Barang">
              </div>
              <div class="col-6">
                <input type="number" class="form-control" id="harga_per_satuan_barang" name="harga_per_satuan_barang" placeholder="Harga Per Satuan Barang">
              </div>
            </div>
            <br/>
            <div class="row">
              <div class="col-9">
              </div>
              <div class="col-3">
                <input type = "hidden" id = "aksi" value="simpan">
                <input type = "hidden" id = "uuid" name="uuid">
                <button type="submit" id = "save" class="btn btn-primary"><i class="fa fa-save"></i> Simpan</button>
                <button type="button" id = "reset1" class="btn btn-warning"><i class="fa fa-redo"></i> Reset</button>
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

  <div class="row">
    <div class="col-md-12">
      <div class="card card-primary">
        <div class="card-header">
          <h3 class="card-title">Data Management</h3>
        </div>
            @csrf
            <div class="card-body">
              <div class="form-group">
                <div class="row">
                  <div class="col-3">
                  </div>
                  <div class="col-6">
                    <button type="button" id = "backup" class="btn btn-success"><i class="fa fa-download"></i> Export</button>
                    <button type="button" id = "import" class="btn btn-primary"><i class="fa fa-upload"></i> Import</button>
                    <button type="button" id = "import" class="btn btn-danger"><i class="fa fa-trash"></i> Kosongkan Data</button>
                  </div>
                  <div class="col-3">
                  </div>
                </div>
              </div>
            </div>
        </div>
      </div>
    </div>

<div class="row">
  <div class="col-md-12">
    <table id="barang" class="table table-bordered table-striped">
      <thead>
        <tr>
          <th>No</th>
          <th>Kode Barang</th>
          <th>Nama Barang</th>
          <th>Kategori Barang</th>
          <th>Manufaktur Barang</th>
          <th>Stok Barang</th>
          <th>Harga Barang</th>
          <th>Aksi</th>
        </tr>
      </thead>
      <tfoot>
        <tr>
          <td>No</td>
          <td>Kode Barang</td>
          <td>Nama Barang</td>
          <td>Kategori Barang</td>
          <td>Manufaktur Barang</td>
          <td>Stok Barang</td>
          <td>Harga Barang</td>
          <td>Aksi</td>
        </tr>
      </tfoot>
    </table>
  </div>
</div>


@push('script')
<script>
$(document).ready(function() {

  $('.select2').select2({
    placeholder: "-- PILIH KATEGORI --",
    allowClear: true,
    theme: 'bootstrap4'
  });

  var _url = '{{ route("barang.dataTables") }}'
  var _table = $('#barang')
  var _column = ['DT_RowIndex','kode_barang','nama_barang','kategori_barang.nama_kategori','manufaktur_barang','jumlah_stok_barang','harga_per_satuan_barang','action']
  var _form_id = $('#barang_form')
  CustomDataTables(_table,_url,null,_column)

  _form_id.on('submit', function() {
    event.preventDefault();
    var _url_add = '{{ route("barang.store") }}'
    var _url_upd = '{{ route("barang.update") }}'
    let _table = $('#barang')
    let _form_id = $('#barang_form')
    let _form = new FormData($(this)[0]);
    let _select2 = $('.select2');
    if($('#aksi').val() == 'simpan') {
        SendData(_form, _url_add, _form_id, _select2, _table)
    } else if($('#aksi').val() == 'update') {
      SendData(_form, _url_upd, _form_id, _select2, _table)
      $('#aksi').val('simpan');
    }
  });

  $('#reset1').click(function() {
    $('.select2').val('').trigger('change');
    $('#barang_form')[0].reset();
    $('#aksi').val('simpan');
  });

  $(document).on('click','.delete',function() {
    var _url_delete = $(this).attr('id')
    // console.log(_url_delete)
    DeleteData(_url_delete,_table)
  });

  $(document).on('click','.update',function() {
    var _url_update = $(this).attr('id')
    console.log(_url_update);
    // console.log(_url_delete)
    $(window).scrollTop(0);
    $('#aksi').val('update');
    $.ajax({
      url: _url_update,
      dataType: "json",
      success: function(data) {
        $('#uuid').val(data.data.uuid);
        $('#kode_barang').val(data.data.kode_barang);
        $('#nama_barang').val(data.data.nama_barang);
        $('#manufaktur_barang').val(data.data.manufaktur_barang);
        $('.select2').val(data.data.uuid_kategori).trigger('change');
        $('#jumlah_stok_barang').val(data.data.jumlah_stok_barang);
        $('#harga_per_satuan_barang').val(data.data.harga_per_satuan_barang);
      }
    });
  });
});

</script>
@endpush

@endsection