routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::middleware(['notLogin'])->group(function() {
  Route::get('dashboard','MainController@index')->name('dashboard.index');
  Route::post('loglogin/dataTables','MainController@datatables')->name('loglogin.dataTables');
  Route::post('auth/requestLoginUser/{auth}','AuthController@UserRequestLogin')->name('auth.requestLoginUser');
  Route::resource('kategori','KategoriController');
  Route::resource('barang','BarangController');

  Route::middleware(['slugpermission'])->group(function() {
    Route::resource('pegawai','PegawaiController');
    Route::resource('jabatan','JabatanController');
    Route::get('skp','StatusKepegawaianController@index')->name('skp.index');
    Route::post('jabatan/update','JabatanController@update')->name('jabatan.update');
    Route::post('pegawai/update','PegawaiController@update')->name('pegawai.update');
    Route::post('pegawai/dataTables','PegawaiController@datatables')->name('pegawai.dataTables');
    Route::post('jabatan/dataTables','JabatanController@datatables')->name('jabatan.dataTables');
    Route::post('skp/dataTables','StatusKepegawaianController@datatables')->name('skp.dataTables');
    Route::post('pegawai/requestAct/{pegawai}','PegawaiController@requestAct')->name('pegawai.requestAct');
    Route::post('skp','StatusKepegawaianController@store')->name('skp.store');
    Route::get('skp/{skp}/edit','StatusKepegawaianController@edit')->name('skp.edit');
    Route::post('skp/update','StatusKepegawaianController@update')->name('skp.update');
    Route::delete('skp/{skp}','StatusKepegawaianController@destroy')->name('skp.destroy');
  });

  Route::get('pegawai/{pegawai}','PegawaiController@show')->name('pegawai.show');
  Route::post('barang/update','BarangController@update')->name('barang.update');
  Route::post('kategori/dataTables','KategoriController@datatables')->name('kategori.dataTables');
  Route::post('barang/dataTables','BarangController@datatables')->name('barang.dataTables');
  Route::get('leaflet/maps','LeafletController@index')->name('leaflet.index');
});

app/Models/Pegawai.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Pegawai extends Main
{
    protected $table = 'kepegawaian.pegawai';

    protected $fillable = [
      'nip_pegawai',
      'nama_pegawai',
      'uuid_jabatan',
      'tempat_lahir_pegawai',
      'tanggal_lahir_pegawai',
      'agama_pegawai',
      'jenis_kelamin_pegawai',
      'status_nikah_pegawai',
      'telepon1_pegawai',
      'telepon2_pegawai',
      'email_pegawai',
      'alamat_pegawai',
      'uuid_status',
    //  'lama_tahun_bekerja_pegawai',
      'foto_pegawai',
      'is_aktif',
      'is_akses'
    ];

    public static function getAgama($idAgama = null) {
      $agama = array(
        1 => 'Islam',
        2 => 'Kristen Protestan',
        3 => 'Kristen Katholik',
        4 => 'Hindu',
        5 => 'Budha',
        6 => 'Konghucu'
      );

      if(!empty($idAgama)) {
        return $agama[$idAgama];
      } else {
          return $agama;
      }
    }

    public static function getSatusNikah($idNikah = null) {
      $nikah = array(
        1 => 'Belum Menikah',
        2 => 'Menikah',
        3 => 'Cerai Hidup',
        4 => 'Cerai Mati'
      );

      if(!empty($idNikah)) {
        return $nikah[$idNikah];
      } else {
        return $nikah;
      }
    }

    public static function getJenisKelamin($idJK = null) {
      $jk = array(
        'L' => 'Laki-laki',
        'P' => 'Perempuan'
      );

      if(!empty($idJK)) {
        return $jk[$idJK];
      } else {
        return $jk;
      }
    }

    public static function getStatusPegawai($idSP = null) {
      // $SP = array(
      //   'Pegawai Tetap' => array(
      //     'lama-kerja' => null,
      //     'gaji-pokok' => 2500000
      //   ),
      //   'Pegawai Kontrak' => array(
      //     'lama-kerja' => 1,
      //     'gaji-pokok' => 18
      //   )
      // )
    }

    public function StatusKepegawaian() {
      return $this->belongsTo(StatusKepegawaian::class,'uuid_status','uuid');
    }

    public function Jabatan() {
      return $this->belongsTo(Jabatan::class,'uuid_jabatan','uuid');
    }

    public function User() {
      return $this->belongsTo(User::class,'uuid','uuid_pegawai');
    }
}

app/Http/Controllers/PegawaiController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Pegawai;
use App\Models\StatusKepegawaian;
use App\Models\Jabatan;
use App\Models\Validation;
use App\Models\User;
use App\Models\Role;
use DB;
use DataTables;
use Validator;
use Storage;
use Hash;
use Auth;

class PegawaiController extends Controller
{

    public function datatables() {
      $query = Pegawai::with([
        'StatusKepegawaian',
        'Jabatan'
        ])->select('pegawai.*')->where('uuid','!=',Auth::user()->pegawai->uuid)->where('nip_pegawai','!=','admin');
        return Datatables::of($query)
               ->addIndexColumn()
               ->addColumn('action', function($data) {
                 $button = '<button type="button" name="view" id="'.route('pegawai.show',$data->uuid).'" class="view btn btn-xs btn-primary" data-toggle="tooltip" title="Lihat Data"><i class = "fa fa-eye"></i></button>';
                 $button .= '<button type="button" name="delete" id="'.route('pegawai.destroy',$data->uuid).'" class="delete btn btn-danger btn-xs" data-toggle="tooltip" title="Hapus"><i class = "fa fa-trash"></i></button> ';
                 $button .= '<button type="button" name="update" id="'.route('pegawai.edit',$data->uuid).'" class="update btn btn-warning btn-xs" data-toggle="tooltip" title="Edit"><i class = "fa fa-edit"></i></button>';
                 if($data->is_akses == 0) {
                    $button .= '<button type="button" name="update" id="'.route('auth.requestLoginUser',$data->uuid).'" class="akses btn btn-success btn-xs" data-toggle="tooltip" title="Beri Akses"><i class = "fa fa-user"></i></button>';
                 }
                 return $button;
               })
               ->rawColumns(['action'])
               ->make(true);
    }

    public function requestAct($act) {

      if($act == 'add') {
        return response()->json([
          'response' => 'success'
        ]);
      } else if($act == 'upd') {
        return response()->json([
          'response' => 'success'
        ]);
      } else if($act == 'read') {
        return response()->json([
          'response' => 'success'
        ]);
      } else {
        return response()->json([
          'response' => 'failed'
        ]);
      }
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        return view('AdminLTE.pages.pegawai.list');

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $data['title'] = 'Tambah Pegawai';
        $data['action'] = 'simpan';
        $data['agama'] = Pegawai::getAgama();
        $data['statusnikah'] = Pegawai::getSatusNikah();
        $data['jk'] = Pegawai::getJenisKelamin();
        $data['jabatan'] = DB::table('kepegawaian.jabatan')
                           ->select('uuid','nama_jabatan')
                           ->where('deleted_at',null)
                           ->get();
        $data['skp'] = DB::table('kepegawaian.status_kepegawaian')
                           ->select('uuid','nama_status_kepegawaian')
                           ->where('deleted_at',null)
                           ->get();
        $data['role'] = DB::table('master.role')
                            ->select('uuid','nama_role')
                            ->where('deleted_at',null)
                            ->get();
        $data['allow-button'] = true;
        return view('AdminLTE.pages.pegawai.form',compact('data'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $rules = array(
          'nip_pegawai' => 'required|min:15',
          'nama_pegawai' => 'required',
          'uuid_jabatan' => 'required',
          'tempat_lahir' => 'required',
          'tanggal_lahir' => 'required',
          'agama' => 'required',
          'jk' => 'required',
          'snikah' => 'required',
          'telepon1' => 'required|numeric',
          'telepon2' => 'required|numeric',
          'email' => 'required',
          'alamat' => 'required',
          'statuskep' => 'required',
          'foto' => 'required|image'
        );
        $errors = Validator::make(
          $request->all(),
          $rules,
          Validation::ValidationMessage()
        );

        if($errors->fails()) {
          return response()->json([
            'response' => 'failed',
            'header' => 'Gagal',
            'messages' => $errors->errors()->all(),
          ]);
        }

        DB::beginTransaction();

        $image_path = '/assets/photos/pegawai/';

        $request->request->add([
          'nip_pegawai' => $request->nip_pegawai,
          'nama_pegawai' => $request->nama_pegawai,
          'uuid_jabatan' => $request->uuid_jabatan,
          'tempat_lahir_pegawai' => $request->tempat_lahir,
          'tanggal_lahir_pegawai' => $request->tanggal_lahir,
          'agama_pegawai' => $request->agama,
          'jenis_kelamin_pegawai' => $request->jk,
          'status_nikah_pegawai' => $request->snikah,
          'telepon1_pegawai' => $request->telepon1,
          'telepon2_pegawai' => $request->telepon2,
          'email_pegawai' => $request->email,
          'alamat_pegawai' => $request->alamat,
          'uuid_status' => $request->statuskep,
          //'lama_tahun_bekerja_pegawai' => StatusKepegawaian::where('uuid',$request->statuskep)->firstOrFail()->lama_kerja_status_kepegawaian,
          'foto_pegawai' => '/'.$request->file('foto')->storeAs($image_path,$request->nip_pegawai.'.'.$request->foto->extension())
        ]);

        // $this->beginQueryLog();
        $insert = Pegawai::create($request->all());

        if($insert) {
          $pegawai = Pegawai::where('nip_pegawai',$request->nip_pegawai)->firstOrFail();
          if(!empty($request->role)) {
            User::create([
              'uuid_pegawai' => $pegawai->uuid,
              'username' => $pegawai->nip_pegawai,
              'password' => Hash::make($pegawai->tanggal_lahir_pegawai),
              'uuid_role' => $request->role
            ]);
            $pegawai->update([
              'is_akses' => 1
            ]);
          }
          // dd($this->endQueryLog());
          DB::commit();
          return response()->json([
            'response' => 'success',
            'header' => 'Sukses',
            'messages' => 'Data Sukses Tersimpan',
            'post_data' => $request->all()
          ]);
        } else if(!$insert) {
          DB::rollback();
          return response()->json([
            'response' => 'failed',
            'header' => 'Gagal',
            'messages' => 'Data Gagal Tersimpan',
          ]);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($uuid)
    {
        //
        if(Auth::user()->pegawai->uuid != $uuid) {
          return abort(404);
        }

        $data['action'] = 'update';
        $data['agama'] = Pegawai::getAgama();
        $data['statusnikah'] = Pegawai::getSatusNikah();
        $data['jk'] = Pegawai::getJenisKelamin();
        $data['jabatan'] = DB::table('kepegawaian.jabatan')
                           ->select('uuid','nama_jabatan')
                           ->where('deleted_at',null)
                           ->get();
        $data['skp'] = DB::table('kepegawaian.status_kepegawaian')
                           ->select('uuid','nama_status_kepegawaian')
                           ->where('deleted_at',null)
                           ->get();
        $data['role'] = DB::table('master.role')
                            ->select('uuid','nama_role')
                            ->where('deleted_at',null)
                            ->get();
        $data['pegawai'] = Pegawai::where('uuid',$uuid)->firstOrFail();
        $data['title'] = 'Profile Pegawai '.$data['pegawai']->nama_pegawai;
        $data['show'] = 'readonly';
        $data['allow-button'] = false;
        return view('AdminLTE.pages.pegawai.form',compact('data'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($uuid)
    {
        //
        $data['action'] = 'update';
        $data['agama'] = Pegawai::getAgama();
        $data['statusnikah'] = Pegawai::getSatusNikah();
        $data['jk'] = Pegawai::getJenisKelamin();
        $data['jabatan'] = DB::table('kepegawaian.jabatan')
                           ->select('uuid','nama_jabatan')
                           ->where('deleted_at',null)
                           ->get();
        $data['skp'] = DB::table('kepegawaian.status_kepegawaian')
                           ->select('uuid','nama_status_kepegawaian')
                           ->where('deleted_at',null)
                           ->get();
        $data['role'] = DB::table('master.role')
                            ->select('uuid','nama_role')
                            ->where('deleted_at',null)
                            ->get();
        $data['pegawai'] = Pegawai::where('uuid',$uuid)->firstOrFail();
        $data['title'] = 'Edit Pegawai '.$data['pegawai']->nama_pegawai;
        $data['readonly'] = 'readonly';
        $data['allow-button'] = true;
        return view('AdminLTE.pages.pegawai.form',compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        //
        $rules = array(
          'nama_pegawai' => 'required',

resources/views/AdminLTE/pages/pegawai/list.blade.php
@extends('AdminLTE.app')

@section('content')

<div class="row">
  <div class="col-md-12">
    <div class="card card-primary">
      <div class="card-header">
        <h3 class="card-title">Data Management</h3>
      </div>
          @csrf
          <div class="card-body">
            <div class="form-group">
              <div class="row">
                <div class="col-3">
                </div>
                <div class="col-6">
                  <button type="button" id = "backup" class="btn btn-success"><i class="fa fa-download"></i> Export</button>
                  <button type="button" id = "import" class="btn btn-primary"><i class="fa fa-upload"></i> Import</button>
                  <button type="button" id = "import" class="btn btn-danger"><i class="fa fa-trash"></i> Kosongkan Data</button>
                </div>
                <div class="col-3">
                </div>
              </div>
            </div>
          </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <div class="row">
        <div class="col-10">
        </div>
        <div class="col-2">
          <button type="button" id = "tambah" class="btn btn-sm btn-success float-right"><i class="fa fa-plus"></i> Tambah</button>
        </div>
      </div>
    </div>
  </div>

  <br/>

<div class="row">
  <div class="col-md-12">
    <table id="pegawai" class="table table-bordered table-striped">
      <thead>
        <tr>
          <th>No</th>
          <th>NIP Pegawai</th>
          <th>Nama Pegawai</th>
          <th>Jabatan Pegawai</th>
          <th>Waktu Input</th>
          <th>Aksi</th>
        </tr>
      </thead>
      <tfoot>
        <tr>
          <td>No</td>
          <td>NIP Pegawai</td>
          <td>Nama Pegawai</td>
          <td>Jabatan Pegawai</td>
          <td>Waktu Input</td>
          <td>Aksi</td>
        </tr>
      </tfoot>
    </table>
  </div>
</div>

@push('script')
<script>
$(document).ready(function() {

  var _url = '{{ route("pegawai.dataTables") }}'
  var _table = $('#pegawai')
  var _column = ['DT_RowIndex','nip_pegawai','nama_pegawai','jabatan.nama_jabatan','created_at','action']
  // var _form_id = $('#kategori_form')
  CustomDataTables(_table,_url,null,_column)

  $('#tambah').click(function(){
    // setTimeout(function() {
      $.ajax({
        url: '{{ route("pegawai.requestAct","add") }}',
        method: 'POST',
        success: function(data) {
          if(data.response == 'success') {
            window.location.href = '{{ route("pegawai.create") }}';
          } else if(data.response == 'failed'){
            Swal.fire({
              type: 'error',
              title: 'Oops...',
              text: 'Gagal Memanggil Halaman',
              icon: 'error'
            });
          }
        },
        error: function(data) {
          Swal.fire({
            type: 'error',
            title: 'Oops...',
            text: 'Error',
            icon: 'error'
          });
        }
      });
    // }, 5000);
  })

  // _form_id.on('submit', function() {
  //   event.preventDefault();
  //   var _url_add = '{{ route("kategori.store") }}'
  //   let _table = $('#kategori')
  //   let _form_id = $('#kategori_form')
  //   let _form = new FormData($(this)[0]);
  //   SendData(_form, _url_add, _form_id, null, _table)
  // });
  //
  $(document).on('click','.delete',function() {
    var _url_delete = $(this).attr('id')
    // console.log(_url_delete)
    DeleteData(_url_delete,_table)
  });

  $(document).on('click','.update',function() {
    var _url_update = $(this).attr('id')
    $.ajax({
      url: '{{ route("pegawai.requestAct","upd") }}',
      method: 'POST',
      success: function(data) {
        if(data.response == 'success') {
          window.location.href = _url_update;
        } else if(data.response == 'failed'){
          Swal.fire({
            type: 'error',
            title: 'Oops...',
            text: 'Gagal Memanggil Halaman',
            icon: 'error'
          });
        }
      },
      error: function(data) {
        Swal.fire({
          type: 'error',
          title: 'Oops...',
          text: 'Error',
          icon: 'error'
        });
      }
    });
  });

  $(document).on('click','.view',function() {
    var _url_view = $(this).attr('id')
    $.ajax({
      url: '{{ route("pegawai.requestAct","read") }}',
      method: 'POST',
      success: function(data) {
        if(data.response == 'success') {
          window.location.href = _url_view;
        } else if(data.response == 'failed'){
          Swal.fire({
            type: 'error',
            title: 'Oops...',
            text: 'Gagal Memanggil Halaman',
            icon: 'error'
          });
        }
      },
      error: function(data) {
        Swal.fire({
          type: 'error',
          title: 'Oops...',
          text: 'Error',
          icon: 'error'
        });
      }
    });
  });

  $(document).on('click','.akses',function() {
    var _url_akses = $(this).attr('id')
    // console.log(_url_delete)
    Swal.fire({
      title: 'Apakah Anda Yakin Menambahkan Akses ?',
      // showDenyButton: true,
      showCancelButton: true,
      confirmButtonText: `Simpan`,
      confirmButtonColor: '#d33',
      // denyButtonText: `Kembali`,
      icon: 'question'
    }).then((result) =>{
      if(result.isConfirmed) {
        $.ajax({
          url: _url_akses,
          method: "POST",
          dataType: "json",
          success:function(data) {
            var count
            if(data.response == 'success') {
              Swal.fire(
                data.header,
                data.messages,
                'success'
              )
              $('#pegawai').DataTable().ajax.reload();
            } else if(data.response == 'failed') {
              var messages = data.messages.join('<br/>')
              //console.log(messages)
              Swal.fire(
                data.header,
                messages,
                'error'
              )
            }
          }
        });
      } else if(result.isDenied) {
        Swal.fire('Changes are not saved', '', 'info')
      }
    })
  });

});

</script>
@endpush

@endsection