routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::middleware(['notLogin'])->group(function() {
  Route::get('dashboard','MainController@index')->name('dashboard.index');
  Route::post('loglogin/dataTables','MainController@datatables')->name('loglogin.dataTables');
  Route::post('auth/requestLoginUser/{auth}','AuthController@UserRequestLogin')->name('auth.requestLoginUser');
  Route::resource('kategori','KategoriController');
  Route::resource('barang','BarangController');

  Route::middleware(['slugpermission'])->group(function() {
    Route::resource('pegawai','PegawaiController');
    Route::resource('jabatan','JabatanController');
    Route::get('skp','StatusKepegawaianController@index')->name('skp.index');
    Route::post('jabatan/update','JabatanController@update')->name('jabatan.update');
    Route::post('pegawai/update','PegawaiController@update')->name('pegawai.update');
    Route::post('pegawai/dataTables','PegawaiController@datatables')->name('pegawai.dataTables');
    Route::post('jabatan/dataTables','JabatanController@datatables')->name('jabatan.dataTables');
    Route::post('skp/dataTables','StatusKepegawaianController@datatables')->name('skp.dataTables');
    Route::post('pegawai/requestAct/{pegawai}','PegawaiController@requestAct')->name('pegawai.requestAct');
    Route::post('skp','StatusKepegawaianController@store')->name('skp.store');
    Route::get('skp/{skp}/edit','StatusKepegawaianController@edit')->name('skp.edit');
    Route::post('skp/update','StatusKepegawaianController@update')->name('skp.update');
    Route::delete('skp/{skp}','StatusKepegawaianController@destroy')->name('skp.destroy');
  });

  Route::get('pegawai/{pegawai}','PegawaiController@show')->name('pegawai.show');
  Route::post('barang/update','BarangController@update')->name('barang.update');
  Route::post('kategori/dataTables','KategoriController@datatables')->name('kategori.dataTables');
  Route::post('barang/dataTables','BarangController@datatables')->name('barang.dataTables');
  Route::get('leaflet/maps','LeafletController@index')->name('leaflet.index');
});

app/Models/Jabatan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Jabatan extends Main
{
    protected $table = 'kepegawaian.jabatan';

    protected $fillable = [
      'kode_jabatan',
      'nama_jabatan'
    ];
}

app/Http/Controllers/JabatanController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Jabatan;
use App\Models\Validation;
use DB;
use DataTables;
use Validator;

class JabatanController extends Controller
{

    public function datatables() {
      $query = Jabatan::query();
      return Datatables::of($query)
             ->addIndexColumn()
             ->addColumn('action', function($data) {
               $button = '<button type="button" name="delete" id="'.route('jabatan.destroy',$data->uuid).'" class="delete btn btn-danger btn-sm"><i class = "fa fa-trash"></i></button> ';
               $button .= '<button type="button" name="update" id="'.route('jabatan.edit',$data->uuid).'" class="update btn btn-warning btn-sm"><i class = "fa fa-edit"></i></button>';
               return $button;
             })
             ->rawColumns(['action'])
             ->make(true);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        return view('AdminLTE.pages.jabatan.list');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $rules = array(
          'kode_jabatan' => 'required|min:15',
          'nama_jabatan' => 'required'
        );
        $errors = Validator::make(
          $request->all(),
          $rules,
          Validation::ValidationMessage()
        );

        if($errors->fails()) {
          return response()->json([
            'response' => 'failed',
            'header' => 'Gagal',
            'messages' => $errors->errors()->all(),
          ]);
        }

        $request->request->add([
          'kode_jabatan' => $request->kode_jabatan,
          'nama_jabatan' => $request->nama_jabatan
        ]);

        $insert = Jabatan::create($request->all());

        if($insert) {
          return response()->json([
            'response' => 'success',
            'header' => 'Sukses',
            'messages' => 'Data Sukses Tersimpan',
            'post_data' => $request
          ]);
        } else if(!$insert) {
          return response()->json([
            'response' => 'failed',
            'header' => 'Gagal',
            'messages' => 'Data Gagal Tersimpan Silahkan Coba Lagi',
          ]);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($uuid)
    {
        //
        $data = Jabatan::where('uuid',$uuid)->first();
        return response()->json([
          'response' => 'success',
          'data' => $data
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        //
        $rules = array(
          'kode_jabatan' => 'required|min:15',
          'nama_jabatan' => 'required'
        );
        $errors = Validator::make(
          $request->all(),
          $rules,
          Validation::ValidationMessage()
        );

        if($errors->fails()) {
          return response()->json([
            'response' => 'failed',
            'header' => 'Gagal',
            'messages' => $errors->errors()->all(),
          ]);
        }

        $request->request->add([
          'kode_jabatan' => $request->kode_jabatan,
          'nama_jabatan' => $request->nama_jabatan
        ]);

        $jabatan = Jabatan::where('uuid',$request->uuid)->first();

        $update = $jabatan->update($request->all());

        if($update) {
          return response()->json([
            'response' => 'success',
            'header' => 'Sukses',
            'messages' => 'Data Sukses Dirubah',
            'post_data' => $request
          ]);
        } else if(!$insert) {
          return response()->json([
            'response' => 'failed',
            'header' => 'Gagal',
            'messages' => 'Data Gagal Dirubah Silahkan Coba Lagi',
          ]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($uuid)
    {
        //
        $data = Jabatan::where('uuid',$uuid)->firstOrFail();
        $delete = $data->delete();
        if($delete) {
          return response()->json([
            'response' => 'success',
            'header' => 'Sukses',
            'messages' => 'Data Sukses Terhapus'
          ]);
        } else if(!$delete) {
          return response()->json([
            'response' => 'failed',
            'header' => 'Gagal',
            'messages' => 'Data Gagal Terhapus'
          ]);
        }
    }
}

resources/views/AdminLTE/pages/jabatan/list.blade.php
@extends('AdminLTE.app')

@section('content')

<div class="row">
  <div class="col-md-12">
    <div class="card card-primary">
      <div class="card-header">
        <h3 class="card-title">Form Jabatan</h3>
      </div>
        <form id="jabatan_form" method="post" enctype="multipart/form-data">
          @csrf
          <div class="card-body">
            <div class="form-group">
              <div class="row">
                <div class="col-4">
                  <input type="text" class="form-control" id="kode_jabatan" name="kode_jabatan" placeholder="Kode Jabatan" maxlength="15">
                </div>
                <div class="col-5">
                  <input type="text" class="form-control" id="nama_jabatan" name="nama_jabatan" placeholder="Nama Jabatan">
                </div>
                <div class="col-3">
                  <input type = "hidden" id = "aksi" value="simpan">
                  <input type = "hidden" id = "uuid" name="uuid">
                  <button type="button" id = "reset1" class="btn btn-warning float-right"><i class="fa fa-redo"></i> Reset</button>
                  <button type="submit" id = "save" class="btn btn-primary float-right"><i class="fa fa-save"></i> Simpan</button>
                </div>
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <div class="card card-primary">
        <div class="card-header">
          <h3 class="card-title">Data Management</h3>
        </div>
          <form id="jabatan_form" method="post" enctype="multipart/form-data">
            @csrf
            <div class="card-body">
              <div class="form-group">
                <div class="row">
                  <div class="col-3">
                  </div>
                  <div class="col-6">
                    <button type="button" id = "backup" class="btn btn-success"><i class="fa fa-download"></i> Export</button>
                    <button type="button" id = "import" class="btn btn-primary"><i class="fa fa-upload"></i> Import</button>
                    <button type="button" id = "import" class="btn btn-danger"><i class="fa fa-trash"></i> Kosongkan Data</button>
                  </div>
                  <div class="col-3">
                  </div>
                </div>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>

<div class="row">
  <div class="col-md-12">
    <table id="jabatan" class="table table-bordered table-striped">
      <thead>
        <tr>
          <th>No</th>
          <th>Kode Jabatan</th>
          <th>Nama Jabatan</th>
          <th>Waktu Input</th>
          <th>Aksi</th>
        </tr>
      </thead>
      <tfoot>
        <tr>
          <td>No</td>
          <td>Kode Jabatan</td>
          <td>Nama Jabatan</td>
          <td>Waktu Input</td>
          <td>Aksi</td>
        </tr>
      </tfoot>
    </table>
  </div>
</div>


@push('script')
<script>
$(document).ready(function() {

  var _url = '{{ route("jabatan.dataTables") }}'
  var _table = $('#jabatan')
  var _column = ['DT_RowIndex','kode_jabatan','nama_jabatan','created_at','action']
  var _form_id = $('#jabatan_form')
  CustomDataTables(_table,_url,null,_column)

  _form_id.on('submit', function() {
    event.preventDefault();
    var _url_add = '{{ route("jabatan.store") }}';
    var _url_upd = '{{ route("jabatan.update") }}';
    let _table = $('#jabatan')
    let _form_id = $('#jabatan_form')
    let _form = new FormData($(this)[0]);
    if($('#aksi').val() == 'simpan') {
        SendData(_form, _url_add, _form_id, null, _table)
    } else if($('#aksi').val() == 'update') {
      SendData(_form, _url_upd, _form_id, null, _table)
      $('#aksi').val('simpan');
    }
  });

  $('#reset1').click(function() {
    $('#jabatan_form')[0].reset();
    $('#aksi').val('simpan');
  });

  $(document).on('click','.delete',function() {
    var _url_delete = $(this).attr('id')
    // console.log(_url_delete)
    DeleteData(_url_delete,_table)
  });

  $(document).on('click','.update',function() {
    var _url_update = $(this).attr('id')
    console.log(_url_update);
    // console.log(_url_delete)
    $(window).scrollTop(0);
    $('#aksi').val('update');
    $.ajax({
      url: _url_update,
      dataType: "json",
      success: function(data) {
        $('#uuid').val(data.data.uuid);
        $('#kode_jabatan').val(data.data.kode_jabatan);
        $('#nama_jabatan').val(data.data.nama_jabatan);
      }
    });
  });

});

</script>
@endpush

@endsection